import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Component/Shared/Navbar";
import Footer from "./Component/Shared/Footer";
import { AuthProvider } from "./Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Transport web app",
  description: "Generated by create next app",
  icons: {
    icon: "/bus-clipart-green-4.png", // Path to your favicon
    shortcut: "/bus-clipart-green-4.png", // Optional for shortcut icons
    apple: "/bus-clipart-green-4.png", // Optional for Apple devices
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
